from __future__ import annotations

from analyzer.risk_schema import RiskRule


RULESET_VERSION = "1.4.0"


RISK_RULE_OBJECTS = [
    RiskRule(
        id="liability_unlimited",
        category="liability",
        title="Unlimited liability",
        severity=5,
        weight=5,
        rationale="Liability is not capped, exposing a party to potentially unlimited financial risk.",
        patterns=[
            r"\bunlimited\s+liabilit(?:y|ies)\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\bunlimited\b",
            r"\bunlimited\b.{0,80}\bliabilit(?:y|ies)\b",
            r"\bno\s+cap\s+on\s+liabilit(?:y|ies)\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\bno\s+cap\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\bshall\s+not\s+be\s+capped\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\buncapped\b",
            r"\bwithout\s+limitation\s+of\s+liabilit(?:y|ies)\b",
        ],
        negative_patterns=[
            r"\bliabilit(?:y|ies)\b.{0,80}\bcap(?:ped)?\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\blimited\s+to\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\bshall\s+be\s+limited\s+to\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["financial_risk", "high_impact"],
    ),
    RiskRule(
        id="liability_cap_missing_or_unclear",
        category="liability",
        title="Missing or unclear liability cap",
        severity=5,
        weight=5,
        rationale="Absence of a clear liability cap can expose a party to unlimited or unpredictable financial risk.",
        patterns=[
            r"\bliabilit(?:y|ies)\b.{0,80}\b(unlimited|uncapped|no\s+limit)\b",
            r"\bunlimited\s+liabilit(?:y|ies)\b",
            r"\bno\s+cap\s+on\s+liabilit(?:y|ies)\b",
        ],
        negative_patterns=[
            r"\bliabilit(?:y|ies)\b.{0,80}\bcap(?:ped)?\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\blimit(?:ed|ation)?\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["financial_risk", "high_impact"],
    ),
    RiskRule(
        id="liability_cap_present",
        category="liability",
        title="Liability cap present",
        severity=2,
        weight=1,
        rationale="A defined liability cap can mitigate some financial exposure, but should not erase meaningful carve-out exposure.",
        patterns=[
            r"\bliabilit(?:y|ies)\b.{0,100}\bshall\s+not\s+exceed\b",
            r"\bliabilit(?:y|ies)\b.{0,100}\bshall\s+be\s+limited\s+to\b",
            r"\bliabilit(?:y|ies)\b.{0,100}\bcap(?:ped)?\s+at\b",
            r"\baggregate\s+liabilit(?:y|ies)\b.{0,100}\b(?:shall\s+not\s+exceed|limited\s+to)\b",
            r"\btotal\s+liabilit(?:y|ies)\b.{0,100}\b(?:shall\s+not\s+exceed|limited\s+to)\b",
            r"\bliability\s+cap\b",
            r"\bliability\s+is\s+capped\b",
        ],
        negative_patterns=[
            r"\bunlimited\s+liabilit(?:y|ies)\b",
            r"\bno\s+cap\s+on\s+liabilit(?:y|ies)\b",
            r"\bliabilit(?:y|ies)\b.{0,80}\buncapped\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["mitigation", "financial_risk"],
    ),
    RiskRule(
        id="liability_super_cap_carveout",
        category="liability",
        title="Liability cap carve-out or super-cap exposure",
        severity=5,
        weight=5,
        rationale="A liability cap may be materially weakened by carve-outs or super-cap language that preserves unlimited or heightened exposure for key risk categories.",
        patterns=[
            r"\bnothing\s+in\s+this\s+agreement\s+shall\s+limit\b.{0,140}\bliabilit(?:y|ies)\b",
            r"\bliability\s+cap\b.{0,140}\bshall\s+not\s+apply\b",
            r"\bcap\b.{0,140}\bshall\s+not\s+apply\b",
            r"\bnothing\s+excludes?\s+or\s+limits?\b.{0,140}\bliabilit(?:y|ies)\b.{0,140}\b(?:fraud|wilful\s+misconduct|gross\s+negligence|confidentiality|data\s+breach|intellectual\s+property|ip\s+infringement)\b",
            r"\bliabilit(?:y|ies)\b.{0,140}\b(?:fraud|wilful\s+misconduct|gross\s+negligence|confidentiality|data\s+breach|intellectual\s+property|ip\s+infringement)\b.{0,140}\bshall\s+not\s+be\s+limited\b",
            r"\bliabilit(?:y|ies)\b.{0,140}\bshall\s+not\s+be\s+limited\b.{0,140}\b(?:fraud|wilful\s+misconduct|gross\s+negligence|confidentiality|data\s+breach|intellectual\s+property|ip\s+infringement)\b",
            r"\bliabilit(?:y|ies)\b.{0,120}\bcapped\b.{0,120}\bexcept\b.{0,80}\b(?:fraud|gross\s+negligence|wilful\s+misconduct)\b",
            r"\bliabilit(?:y|ies)\b.{0,120}\blimited\b.{0,120}\bexcept\b.{0,80}\b(?:fraud|gross\s+negligence|wilful\s+misconduct)\b",
            r"\bliability\s+is\s+capped\b.{0,120}\bexcept\b.{0,80}\b(?:fraud|gross\s+negligence|wilful\s+misconduct)\b",
            r"\bliabilit(?:y|ies)\b.{0,100}\bexcept\s+in\s+cases?\s+of\b.{0,80}\b(?:fraud|gross\s+negligence|wilful\s+misconduct)\b",
        ],
        negative_patterns=[],
        min_matches=1,
        max_span_chars=200,
        tags=["carveout", "financial_risk", "high_impact"],
    ),

    RiskRule(
        id="unilateral_termination_for_convenience",
        category="termination",
        title="Unilateral termination for convenience",
        severity=5,
        weight=5,
        rationale="Allowing one party to terminate for convenience without equivalent rights creates commercial imbalance and operational uncertainty.",
        patterns=[
            r"\bmay\s+terminate\b.{0,120}\bfor\s+convenience\b",
            r"\bone\s+party\s+may\s+terminate\b.{0,120}\bfor\s+any\s+reason\b",
            r"\bterminate\b.{0,120}\bat\s+any\s+time\b",
    ],
    negative_patterns=[
        r"\beither\s+party\s+may\s+terminate\b",
        r"\bmutual\s+termination\b",
        r"\bboth\s+parties\s+may\s+terminate\b",
    ],
    min_matches=1,
    max_span_chars=140,
    tags=["termination", "asymmetry", "commercial_risk"],

    ),
    RiskRule(
        id="governing_law_foreign_or_unfamiliar",
        category="jurisdiction",
        title="Selected governing law",
        severity=4,
        weight=4,
        rationale="The contract selects a governing law that may affect dispute cost, enforcement route, operational confidence, and escalation planning. Confirm whether the selected forum is commercially workable for this agreement.",
        patterns=[
            r"\b(?:this\s+(?:agreement|contract)|agreement|contract)\b.{0,80}\bgoverned\s+by\s+the\s+laws\s+of\s+\b[a-z][a-z\s,-]{2,80}",
            r"\bgoverning\s+law\s+shall\s+be\s+\b[a-z][a-z\s,-]{2,80}",
            r"\bgoverned\s+by\s+the\s+laws\s+of\s+\b[a-z][a-z\s,-]{2,80}",
        ],
        negative_patterns=[
            r"\bapplicable\s+laws?\b",
            r"\bcomply\s+with\s+all\s+applicable\s+laws?\b",
        ],
        min_matches=1,
        max_span_chars=160,
        tags=["jurisdiction", "dispute_forum", "cross_border_risk"],
    ),
    RiskRule(
        id="jurisdiction_exclusive_foreign_forum",
        category="jurisdiction",
        title="Selected exclusive jurisdiction",
        severity=5,
        weight=5,
        rationale="An exclusive jurisdiction or forum clause may materially affect dispute venue, procedural cost, enforcement route, and escalation confidence. Confirm whether the selected forum is commercially workable for this agreement.",
        patterns=[
            r"\bsubmit\s+to\s+the\s+exclusive\s+jurisdiction\s+of\s+the\s+courts?\s+of\s+\b[a-z][a-z\s,-]{2,80}",
            r"\bexclusive\s+jurisdiction\s+of\s+the\s+courts?\s+of\s+\b[a-z][a-z\s,-]{2,80}",
            r"\bexclusive\s+forum\s+for\s+any\s+dispute\b.{0,80}\b(?:shall\s+be|is)\b.{0,80}\b[a-z][a-z\s,-]{2,80}",
        ],
        negative_patterns=[
            r"\bnon-?exclusive\s+jurisdiction\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["jurisdiction", "dispute_forum", "high_impact"],
    ),
    RiskRule(
        id="jurisdiction_non_exclusive_forum",
        category="jurisdiction",
        title="Non-exclusive dispute forum",
        severity=3,
        weight=2,
        rationale="A non-exclusive jurisdiction clause still affects dispute planning, venue expectations, and escalation confidence, but may be less restrictive than an exclusive forum clause.",
        patterns=[
            r"\bnon-?exclusive\s+jurisdiction\b",
            r"\bcourts?\s+of\s+[a-z][a-z\s,-]{2,80}\s+shall\s+have\s+non-?exclusive\s+jurisdiction\b",
            r"\bsubmit\s+to\s+the\s+non-?exclusive\s+jurisdiction\s+of\b",
        ],
        negative_patterns=[
            r"\bapplicable\s+laws?\b",
            r"\bcomply\s+with\s+all\s+applicable\s+laws?\b",
        ],
        min_matches=1,
        max_span_chars=160,
        tags=["jurisdiction", "dispute_forum", "context_signal"],
    ),
    RiskRule(
        id="arbitration_forum_or_seat",
        category="jurisdiction",
        title="Arbitration seat or forum",
        severity=4,
        weight=3,
        rationale="An arbitration clause or arbitration seat may change dispute process, venue burden, procedural cost, and escalation planning even where the commercial terms otherwise look routine.",
        patterns=[
            r"\bfinally\s+resolved\s+by\s+arbitration\b",
            r"\bany\s+dispute\b.{0,120}\barbitration\b",
            r"\bseat\s+of\s+arbitration\b",
            r"\barbitration\b.{0,100}\bseat(?:ed)?\s+in\b",
            r"\barbitration\b.{0,100}\bvenue\b",
        ],
        negative_patterns=[
            r"\barbitration\s+act\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["jurisdiction", "arbitration", "dispute_forum"],
    ),
    RiskRule(
        id="venue_burden_foreign_court",
        category="jurisdiction",
        title="Operationally burdensome dispute venue",
        severity=4,
        weight=4,
        rationale="A selected court venue may increase operational burden, dispute cost, enforcement friction, and escalation planning burden before a claim is even argued on the merits.",
        patterns=[
            r"\bvenue\s+for\s+any\s+dispute\b.{0,80}\b(?:shall\s+be|is)\b.{0,80}\b[a-z][a-z\s,-]{2,80}",
            r"\b(?:any\s+action|any\s+proceeding|all\s+proceedings)\b.{0,120}\b(?:shall\s+be\s+brought|must\s+be\s+brought)\b.{0,120}\bin\s+the\s+courts?\s+of\s+\b[a-z][a-z\s,-]{2,80}",
        ],
        negative_patterns=[
            r"\bnon-?exclusive\s+jurisdiction\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["jurisdiction", "venue", "cross_border_risk"],
    ),
    RiskRule(
    id="termination_without_notice",
    category="termination",
    title="Termination without notice",
    severity=5,
    weight=5,
    rationale="Termination without notice can cause abrupt operational disruption and financial exposure.",
    patterns=[
        r"\bterminate\b.{0,80}\bwithout\s+notice\b",
        r"\btermination\b.{0,80}\bwithout\s+notice\b",
    ],
    negative_patterns=[
        r"\bwith\s+\d+\s+days?\s+notice\b",
        r"\bwith\s+prior\s+notice\b",
        r"\bon\s+notice\b",
    ],
    min_matches=1,
    max_span_chars=120,
    tags=["termination", "notice", "operational_risk"],
    ),
    RiskRule(
        id="indemnity_broad",
        category="indemnity",
        title="Broad indemnity obligation",
        severity=5,
        weight=5,
        rationale="Broad indemnity obligations may shift substantial third-party or direct loss exposure onto one party.",
        patterns=[
            r"\bindemnif(?:y|ies|ication)\b.{0,100}\ball\s+claims\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,100}\bany\s+and\s+all\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,100}\ball\s+losses\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,100}\ball\s+damages\b",
            r"\bhold\s+harmless\b",
            r"\bdefend,\s*indemnify\s+and\s+hold\s+harmless\b",
        ],
        negative_patterns=[
            r"\bto\s+the\s+extent\s+caused\s+by\b",
            r"\bsolely\s+to\s+the\s+extent\b",
            r"\bexcept\s+to\s+the\s+extent\b",
            r"\bsubject\s+to\s+the\s+liability\s+cap\b",
        ],
        min_matches=1,
        max_span_chars=140,
        tags=["financial_risk", "third_party_risk"],
    ),
    RiskRule(
    id="payment_delay_terms",
    category="payment",
    title="Extended payment terms",
    severity=3,
    weight=3,
    rationale="Long payment cycles may negatively impact cash flow and financial stability.",
    patterns=[
        r"\bpayment\b.{0,40}\bwithin\s+(60|90|120)\s+days\b",
        r"\bpay(?:able|ment)?\b.{0,40}\bwithin\s+(60|90|120)\s+days\b",
        r"\bnet\s+(60|90|120)\b",
    ],
    negative_patterns=[
        r"\bpayment\b.{0,40}\bwithin\s+(7|14|30)\s+days\b",
        r"\bpay(?:able|ment)?\b.{0,40}\bwithin\s+(7|14|30)\s+days\b",
    ],
    min_matches=1,
    max_span_chars=120,
    tags=["cash_flow", "payment_risk"],
),
     RiskRule(
        id="indemnity_one_way",
        category="indemnity",
        title="One-way indemnity",
        severity=4,
        weight=4,
        rationale="A one-way indemnity structure may allocate risk asymmetrically and heavily in favor of the counterparty.",
        patterns=[
            r"\bcustomer\s+shall\s+indemnif(?:y|ies)\b",
            r"\bclient\s+shall\s+indemnif(?:y|ies)\b",
            r"\byou\s+shall\s+indemnif(?:y|ies)\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,80}\bsupplier\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,80}\bprovider\b",
            r"\bindemnif(?:y|ies|ication)\b.{0,80}\bcompany\b",
            r"\bcustomer\s+shall\s+defend\s+and\s+indemnif(?:y|ies)\b",
            r"\bcustomer\s+shall\s+hold\s+(?:the\s+)?supplier\s+harmless\b",
            r"\bcustomer\s+shall\s+hold\s+(?:the\s+)?provider\s+harmless\b",
            r"\bcustomer\s+shall\s+indemnif(?:y|ies)\b.{0,80}\bthird-?party\s+claims\b",
            r"\bclient\s+shall\s+defend\s+and\s+indemnif(?:y|ies)\b",
            r"\byou\s+shall\s+hold\s+(?:the\s+)?company\s+harmless\b",
        ],
        negative_patterns=[
            r"\bmutual\s+indemn(?:it(?:y|ies)|ification)\b",
            r"\beach\s+party\s+shall\s+indemnif(?:y|ies)\b",
            r"\bboth\s+parties\s+shall\s+indemnif(?:y|ies)\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["asymmetry", "counterparty_favoring"],
    ),
    RiskRule(
        id="auto_renewal_silent",
        category="termination",
        title="Silent or automatic renewal",
        severity=3,
        weight=3,
        rationale="Automatic renewal can lock parties into repeated terms unless cancellation windows are monitored closely.",
        patterns=[
            r"\bautomatically\s+renew(?:s|ed|al)?\b",
            r"\bauto-?renew(?:s|ed|al)?\b",
            r"\brenew(?:s|ed|al)?\s+automatically\b",
            r"\bshall\s+renew\s+for\s+successive\s+terms\b",
            r"\bunless\s+terminated\s+before\s+the\s+end\s+of\s+the\s+then-current\s+term\b",
        ],
        negative_patterns=[
            r"\bwill\s+not\s+automatically\s+renew\b",
            r"\bnon-?renew(?:al)?\s+notice\b.{0,80}\bprominent\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["commercial_lockin", "renewal_risk"],
    ),
    RiskRule(
        id="unilateral_price_increase",
        category="payment",
        title="Unilateral price increase right",
        severity=4,
        weight=4,
        rationale="A unilateral fee increase right permits the counterparty to change pricing without balanced renegotiation rights.",
        patterns=[
            r"\bmay\s+increase\s+(?:the\s+)?fees\b",
            r"\bfees?\s+may\s+be\s+increased\b",
            r"\bprice(?:s)?\s+may\s+be\s+changed\b",
            r"\bwe\s+may\s+change\s+our\s+fees\b",
            r"\bsupplier\s+may\s+revise\s+pricing\b",
            r"\bprovider\s+may\s+increase\s+charges\b",
            r"\bsupplier\s+may\s+increase\s+pricing\b",
            r"\bmay\s+increase\s+pricing\b",
            r"\bmay\s+change\s+pricing\b",
            r"\bmay\s+revise\s+pricing\b",
            r"\bmay\s+increase\s+charges\b",
            r"\bpricing\s+may\s+be\s+increased\b",
        ],
        negative_patterns=[
            r"\bsubject\s+to\s+customer\s+consent\b",
            r"\bonly\s+upon\s+renewal\b",
            r"\bwith\s+the\s+customer'?s\s+agreement\b",
            r"\bby\s+mutual\s+agreement\b",
            r"\bin\s+line\s+with\s+cpi\b",
            r"\bconsumer\s+price\s+index\b",
            r"\binflation(?:ary)?\s+adjustment\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["commercial_risk", "price_risk"],
    ),
    RiskRule(
        id="service_suspension_right",
        category="service",
        title="Service suspension right",
        severity=4,
        weight=4,
        rationale="A unilateral service suspension right can disrupt operations and shift leverage to the counterparty.",
        patterns=[
            r"\bservices?\s+may\s+be\s+suspended\b",
            r"\bmay\s+suspend\s+(?:the\s+)?services?\b",
            r"\bsuspend\s+access\b",
            r"\bsuspension\s+without\s+liabilit(?:y|ies)\b",
            r"\bprovider\s+may\s+suspend\b",
            r"\bsupplier\s+may\s+suspend\b",
        ],
        negative_patterns=[
            r"\bonly\s+after\s+reasonable\s+notice\b",
            r"\bexcept\s+where\s+required\s+by\s+law\b",
            r"\bmutual\s+agreement\b",
            r"\bfor\s+non-?payment\b",
            r"\bfor\s+failure\s+to\s+pay\b",
            r"\bfor\s+material\s+breach\b",
            r"\bto\s+prevent\s+security\s+incidents?\b",
            r"\bto\s+protect\s+the\s+security\s+of\s+the\s+services?\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["operational_risk", "counterparty_control"],
    ),
    RiskRule(
        id="broad_sublicensing_right",
        category="licensing",
        title="Broad sublicensing right",
        severity=4,
        weight=4,
        rationale="A broad sublicensing right can dilute control over the licensed rights and expand downstream risk.",
        patterns=[
            r"\bmay\s+sublicense\b",
            r"\bright\s+to\s+sublicense\b",
            r"\bmay\s+grant\s+sublicenses\b",
            r"\bsublicense\s+its\s+rights\b",
            r"\bsublicens(?:e|ing)\b.{0,80}\bwithout\s+restriction\b",
        ],
        negative_patterns=[
            r"\bsubject\s+to\s+customer\s+consent\b",
            r"\bonly\s+to\s+affiliates\b",
            r"\bwith\s+prior\s+written\s+consent\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["control_risk", "ip_risk"],
    ),
    RiskRule(
        id="subcontracting_without_consent",
        category="control",
        title="Subcontracting without consent",
        severity=4,
        weight=4,
        rationale="Allowing subcontracting without consent may reduce visibility and control over who performs the services, increasing operational, security, and compliance risk.",
        patterns=[
            r"\bmay\s+subcontract\b.{0,120}\bwithout\s+(?:prior\s+)?written\s+consent\b",
            r"\bsubcontract(?:ing)?\b.{0,120}\bwithout\s+(?:prior\s+)?written\s+consent\b",
            r"\bfreely\s+subcontract\b",
        ],
        negative_patterns=[
            r"\bmay\s+not\s+subcontract\b",
            r"\bsubcontract(?:ing)?\b.{0,120}\bonly\s+with\s+(?:prior\s+)?written\s+consent\b",
            r"\bprior\s+written\s+consent\s+required\b",
    ],
    min_matches=1,
    max_span_chars=140,
    tags=["subcontracting", "control", "third_party_risk"],
),

    RiskRule(
        id="broad_warranty_disclaimer",
        category="warranty",
        title="Broad warranty disclaimer",
        severity=4,
        weight=4,
        rationale="A broad warranty disclaimer shifts quality and performance risk away from the provider.",
        patterns=[
            r"\bas\s+is\b.{0,60}\bwithout\s+warrant(?:y|ies)\b",
            r"\bprovided\s+as\s+is\b",
            r"\bwithout\s+warrant(?:y|ies)\s+of\s+any\s+kind\b",
            r"\bdisclaims?\s+all\s+warrant(?:y|ies)\b",
            r"\bno\s+warrant(?:y|ies)\b.{0,60}\bexpress\s+or\s+implied\b",
        ],
        negative_patterns=[
            r"\bexcept\s+as\s+expressly\s+set\s+out\b",
            r"\blimited\s+warranty\b",
        ],
        min_matches=1,
        max_span_chars=120,
        tags=["quality_risk", "disclaimer"],
    ),
    RiskRule(
        id="broad_customer_data_use",
        category="data",
        title="Broad customer data use rights",
        severity=4,
        weight=4,
        rationale="Broad rights to use customer data may create confidentiality, privacy, and commercialization concerns.",
        patterns=[
            r"\bmay\s+use\s+customer\s+data\s+for\s+any\s+purpose\b",
            r"\bcustomer\s+data\b.{0,100}\bfor\s+any\s+purpose\b",
            r"\buse\s+customer\s+data\b.{0,100}\bcommercial\b",
            r"\buse\s+data\b.{0,100}\bservice\s+improvement\b",
            r"\bmay\s+use\s+client\s+data\b.{0,100}\bany\s+purpose\b",
        ],
        negative_patterns=[
            r"\bonly\s+to\s+provide\s+the\s+services\b",
            r"\bsubject\s+to\s+applicable\s+data\s+protection\s+law\b",
            r"\banonymi[sz]ed\s+data\s+only\b",
        ],
        min_matches=1,
        max_span_chars=140,
        tags=["data_risk", "privacy_risk"],
    ),
    RiskRule(
        id="liability_consequential_exclusion",
        category="liability",
        title="Consequential damages exclusion",
        severity=1,
        weight=1,
        rationale="An exclusion of consequential or indirect damages is often a market-standard limitation and usually operates as a mild mitigation rather than a core risk trigger.",
        patterns=[
            r"\bneither\s+party\s+shall\s+be\s+liable\s+for\s+consequential\s+or\s+indirect\s+damages\b",
            r"\bno\s+party\s+shall\s+be\s+liable\s+for\s+consequential\s+damages\b",
            r"\bexcludes?\s+consequential\s+damages\b",
            r"\bindirect\s+or\s+consequential\s+damages\b",
        ],
        negative_patterns=[],
        min_matches=1,
        max_span_chars=140,
        tags=["mitigation", "liability_structure"],
    ),

    RiskRule(
        id="termination_for_convenience_counterparty",
        category="termination",
        title="Unilateral termination for convenience",
        severity=4,
        weight=4,
        rationale="A unilateral right allowing the counterparty to terminate for convenience may create revenue instability, operational disruption, and weak commitment certainty.",
        patterns=[
            r"\bmay\s+terminate\b.{0,120}\bfor\s+convenience\b",
            r"\bterminate\b.{0,120}\bat\s+any\s+time\b.{0,120}\bwithout\s+cause\b",
            r"\bmay\s+terminate\b.{0,120}\bwithout\s+cause\b",
            r"\bmay\s+terminate\b.{0,120}\bfor\s+any\s+reason\b",
            r"\bhas\s+the\s+right\s+to\s+terminate\b.{0,120}\bfor\s+convenience\b",
            r"\bmay\s+end\s+this\s+agreement\b.{0,120}\bwithout\s+cause\b",
        ],
        negative_patterns=[
            r"\beither\s+party\s+may\s+terminate\b.{0,120}\bfor\s+convenience\b",
            r"\bneither\s+party\s+may\s+terminate\b",
            r"\bmay\s+terminate\b.{0,120}\bfor\s+material\s+breach\b",
            r"\bmay\s+terminate\b.{0,120}\bfor\s+cause\b",
            r"\bmay\s+terminate\b.{0,120}\bif\s+the\s+other\s+party\s+breaches\b",
            r"\bwritten\s+notice\b.{0,120}\band\s+an\s+opportunity\s+to\s+cure\b",
        ],
        min_matches=1,
        max_span_chars=140,
        tags=["termination_risk", "commercial_control"],
    ),

    RiskRule(
        id="change_of_control_assignment",
        category="assignment",
        title="Change of control or assignment transfer right",
        severity=4,
        weight=4,
        rationale="Assignment or change-of-control transfer rights can move performance, payment, or control obligations to an unexpected counterparty.",
        patterns=[
            r"\bmay\s+assign\b.{0,140}\bchange\s+of\s+control\b.{0,80}\bwithout\s+(?:prior\s+)?(?:written\s+)?consent\b",
            r"\bchange\s+of\s+control\b.{0,140}\bwithout\s+(?:prior\s+)?(?:written\s+)?consent\b",
            r"\bchange\s+of\s+control\b.{0,140}\bdeemed\s+(?:an\s+)?assignment\b.{0,100}\bmay\s+proceed\b",
            r"\bassignment\b.{0,120}\bin\s+connection\s+with\s+(?:a\s+)?change\s+of\s+control\b.{0,80}\bwithout\s+consent\b",
        ],
        negative_patterns=[
            r"\bchange\s+of\s+control\b.{0,120}\brequires?\s+(?:prior\s+)?written\s+consent\b",
            r"\bchange\s+of\s+control\b.{0,120}\bsubject\s+to\s+(?:prior\s+)?written\s+consent\b",
            r"\bmay\s+not\s+assign\b.{0,140}\bchange\s+of\s+control\b",
            r"\bconsent\s+not\s+to\s+be\s+unreasonably\s+withheld\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["assignment", "change_of_control", "counterparty_risk"],
    ),
    RiskRule(
        id="unilateral_amendment_policy_reference",
        category="amendment",
        title="Unilateral amendment or policy incorporation",
        severity=4,
        weight=4,
        rationale="Unilateral amendment or incorporated-policy language can let one party alter operational or commercial obligations without balanced agreement.",
        patterns=[
            r"\bmay\s+(?:modify|amend|update|change)\s+(?:these\s+)?(?:terms|agreement)\b.{0,120}\bat\s+any\s+time\b",
            r"\bwe\s+may\s+(?:modify|amend|update|change)\s+(?:these\s+)?terms\b",
            r"\bsupplier\s+may\s+(?:modify|amend|update|change)\b.{0,120}\bpolic(?:y|ies)\b",
            r"\bpolic(?:y|ies)\b.{0,120}\bincorporated\s+by\s+reference\b.{0,120}\bamended\s+from\s+time\s+to\s+time\b",
            r"\bcustomer\s+shall\s+comply\s+with\b.{0,120}\bpolic(?:y|ies)\b.{0,120}\bas\s+updated\b",
        ],
        negative_patterns=[
            r"\bmay\s+be\s+amended\s+only\s+by\s+(?:a\s+)?written\s+agreement\b",
            r"\bonly\s+by\s+mutual\s+written\s+agreement\b",
            r"\bwith\s+(?:the\s+)?customer'?s\s+prior\s+written\s+consent\b",
            r"\bnotice\b.{0,80}\bright\s+to\s+reject\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["amendment", "policy_reference", "counterparty_control"],
    ),
    RiskRule(
        id="fee_acceleration_late_fee_exposure",
        category="payment",
        title="Fee acceleration or late fee exposure",
        severity=4,
        weight=4,
        rationale="Fee acceleration and aggressive late-fee language can create immediate cash-flow exposure beyond ordinary invoice timing.",
        patterns=[
            r"\ball\s+remaining\s+fees\b.{0,120}\b(?:immediately\s+)?(?:due|payable)\b",
            r"\bfees?\b.{0,120}\baccelerat(?:e|ed|ion)\b",
            r"\blate\s+fees?\b.{0,80}\b(?:1\.5%|one\s+and\s+one-half\s+percent|maximum\s+rate\s+permitted\s+by\s+law)\b",
            r"\boverdue\s+amounts?\b.{0,100}(?:1\.5%|one\s+and\s+one-half\s+percent|maximum\s+rate\s+permitted\s+by\s+law)",
        ],
        negative_patterns=[
            r"\bundisputed\s+overdue\s+amounts?\b.{0,100}\breasonable\s+interest\b",
            r"\bstatutory\s+interest\b",
            r"\bno\s+acceleration\s+of\s+future\s+fees\b",
        ],
        min_matches=1,
        max_span_chars=160,
        tags=["payment_risk", "cash_flow", "acceleration"],
    ),
    RiskRule(
        id="service_credits_sole_remedy",
        category="service",
        title="Service credits as sole remedy",
        severity=4,
        weight=4,
        rationale="Service-credit sole-remedy language may prevent meaningful recovery for service failures even where business impact is larger than the credit.",
        patterns=[
            r"\bservice\s+credits?\b.{0,140}\bsole\s+and\s+exclusive\s+remed(?:y|ies)\b",
            r"\bsole\s+and\s+exclusive\s+remed(?:y|ies)\b.{0,140}\bservice\s+credits?\b",
            r"\bservice\s+level\s+credits?\b.{0,140}\bonly\s+remed(?:y|ies)\b",
            r"\bno\s+other\s+remed(?:y|ies)\b.{0,140}\bservice\s+credits?\b",
            r"\bonly\s+remed(?:y|ies)\b.{0,140}\bservice\s+credits?\b",
        ],
        negative_patterns=[
            r"\bservice\s+credits?\b.{0,120}\bnot\s+(?:the\s+)?exclusive\s+remed(?:y|ies)\b",
            r"\bwithout\s+limiting\s+other\s+remed(?:y|ies)\b",
            r"\bservice\s+credits?\b.{0,120}\bin\s+addition\s+to\s+other\s+remed(?:y|ies)\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["service_level", "remedy_limitation", "operational_risk"],
    ),
    RiskRule(
        id="publicity_name_use_rights",
        category="publicity",
        title="Publicity or name-use rights",
        severity=3,
        weight=3,
        rationale="Publicity and name-use rights can create reputational or confidentiality concerns if consent controls are absent.",
        patterns=[
            r"\bmay\s+use\s+(?:customer|client)'?s?\s+(?:name|logo|marks?)\b",
            r"\bright\s+to\s+use\s+(?:customer|client)'?s?\s+(?:name|logo|marks?)\b",
            r"\bpress\s+release\b.{0,120}\bwithout\s+(?:prior\s+)?(?:written\s+)?consent\b",
            r"\bidentify\s+(?:customer|client)\s+as\s+(?:a\s+)?(?:customer|client)\b.{0,120}\bwithout\s+consent\b",
        ],
        negative_patterns=[
            r"\bmay\s+not\s+use\s+(?:customer|client)'?s?\s+(?:name|logo|marks?)\b",
            r"\bwith\s+(?:prior\s+)?written\s+consent\b",
            r"\bsubject\s+to\s+(?:prior\s+)?written\s+approval\b",
        ],
        min_matches=1,
        max_span_chars=140,
        tags=["publicity", "reputation", "confidentiality"],
    ),
    RiskRule(
        id="intrusive_audit_rights",
        category="audit",
        title="Intrusive audit rights",
        severity=3,
        weight=3,
        rationale="Broad audit rights can create operational disruption, confidentiality exposure, or intrusive access obligations if not bounded.",
        patterns=[
            r"\baudit\b.{0,120}\bbooks\s+and\s+records\b.{0,120}\bat\s+any\s+time\b",
            r"\bright\s+to\s+audit\b.{0,140}\bwithout\s+notice\b",
            r"\binspect\b.{0,120}\bsystems?\b.{0,120}\bat\s+any\s+time\b",
            r"\baudit\b.{0,120}\bunrestricted\s+access\b",
        ],
        negative_patterns=[
            r"\bupon\s+reasonable\s+notice\b.{0,120}\bduring\s+normal\s+business\s+hours\b",
            r"\bnot\s+more\s+than\s+once\s+per\s+year\b",
            r"\bsubject\s+to\s+confidentiality\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["audit", "operational_risk", "confidentiality"],
    ),
    RiskRule(
        id="data_retention_deletion_asymmetry",
        category="data",
        title="Data retention or deletion asymmetry",
        severity=4,
        weight=4,
        rationale="Asymmetric retention or deletion rights can leave customer data held longer than expected or deleted without adequate transition control.",
        patterns=[
            r"\bmay\s+retain\s+customer\s+data\b.{0,140}\bafter\s+termination\b",
            r"\bretain\s+customer\s+data\b.{0,120}\bas\s+long\s+as\s+(?:it|supplier|provider)\s+deems\s+necessary\b",
            r"\bno\s+obligation\s+to\s+(?:return|delete|return\s+or\s+delete)\s+customer\s+data\b",
            r"\bdelete\s+customer\s+data\b.{0,120}\bat\s+(?:its|supplier'?s|provider'?s)\s+discretion\b",
        ],
        negative_patterns=[
            r"\breturn\s+or\s+delete\s+customer\s+data\b.{0,120}\bupon\s+request\b",
            r"\bdelete\s+customer\s+data\b.{0,120}\bwithin\s+\d+\s+days\b",
            r"\bretain\s+customer\s+data\b.{0,120}\bonly\s+as\s+required\s+by\s+law\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["data_risk", "retention", "exit_risk"],
    ),
    RiskRule(
        id="termination_assistance_exit_dependency",
        category="termination",
        title="Termination assistance or exit dependency risk",
        severity=3,
        weight=3,
        rationale="Missing or discretionary termination assistance can make exit, migration, or replacement services dependent on the counterparty's discretion or extra charges.",
        patterns=[
            r"\btermination\s+assistance\b.{0,140}\bsubject\s+to\s+(?:supplier'?s|provider'?s)\s+discretion\b",
            r"\btransition\s+assistance\b.{0,140}\bat\s+(?:supplier'?s|provider'?s)\s+then-current\s+rates\b",
            r"\bno\s+obligation\s+to\s+provide\s+(?:termination|transition|exit)\s+assistance\b",
            r"\bdata\s+migration\b.{0,140}\badditional\s+fees\b.{0,80}\bsole\s+discretion\b",
        ],
        negative_patterns=[
            r"\btermination\s+assistance\b.{0,140}\bincluded\s+at\s+no\s+additional\s+charge\b",
            r"\btransition\s+assistance\b.{0,140}\bfor\s+up\s+to\s+\d+\s+days\b",
            r"\breasonable\s+exit\s+assistance\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["exit_risk", "operational_dependency", "termination"],
    ),
    RiskRule(
        id="survival_clause_risk_concentration",
        category="survival",
        title="Survival clause risk concentration",
        severity=3,
        weight=3,
        rationale="Broad survival language can keep important obligations alive after termination, extending liability, payment, confidentiality, or indemnity exposure.",
        patterns=[
            r"\b(?:indemn(?:ity|ification)|confidentiality|payment|liabilit(?:y|ies))\b.{0,140}\bsurvive\s+termination\b",
            r"\bsurvive\s+termination\b.{0,140}\b(?:indemn(?:ity|ification)|confidentiality|payment|liabilit(?:y|ies))\b",
            r"\ball\s+obligations\b.{0,120}\bsurvive\s+termination\b",
            r"\bsurvival\b.{0,140}\bindefinitely\b",
        ],
        negative_patterns=[
            r"\bsurvive\s+termination\b.{0,120}\bfor\s+\d+\s+(?:months|years)\b",
            r"\bsurvival\b.{0,120}\blimited\s+to\b",
            r"\bexcept\s+as\s+required\s+by\s+law\b",
        ],
        min_matches=1,
        max_span_chars=180,
        tags=["survival", "post_termination", "liability_tail"],
    ),    RiskRule(
        id="assignment_without_consent",
        category="assignment",
        title="Assignment without consent",
        severity=4,
        weight=4,
        rationale="A clause allowing assignment without the other party's consent may transfer rights and obligations to an unknown third party and materially alter commercial risk.",
        patterns=[
            r"\bmay\s+assign\b.{0,120}\bwithout\s+consent\b",
            r"\bassign(?:ment)?\b.{0,120}\bwithout\s+the\s+other\s+party'?s\s+consent\b",
            r"\bassign(?:ment)?\b.{0,120}\bwithout\s+prior\s+written\s+consent\b",
            r"\bfreely\s+assign\b",
            r"\bmay\s+freely\s+assign\b",
            r"\bassign(?:ment)?\b.{0,120}\bto\s+any\s+third\s+party\b",
        ],
        negative_patterns=[
            r"\bconsent\s+not\s+to\s+be\s+unreasonably\s+withheld\b",
            r"\bshall\s+not\s+assign\b.{0,120}\bwithout\s+prior\s+written\s+consent\b",
            r"\bneither\s+party\s+may\s+assign\b.{0,120}\bwithout\s+prior\s+written\s+consent\b",
            r"\bmay\s+assign\b.{0,120}\bto\s+an\s+affiliate\b",
            r"\bmay\s+assign\b.{0,120}\bin\s+connection\s+with\s+a\s+merger\b",
            r"\bmay\s+assign\b.{0,120}\bin\s+connection\s+with\s+a\s+sale\s+of\s+substantially\s+all\s+assets\b",
            r"\bexcept\s+with\s+prior\s+written\s+consent\b",
        ],
        min_matches=1,
        max_span_chars=140,
        tags=["assignment", "change_of_counterparty"],
    ),
]


RULE_NEGATIVE_PATTERNS = {
    rule.id: list(getattr(rule, "negative_patterns", []))
    for rule in RISK_RULE_OBJECTS
}

RULE_TAGS = {
    rule.id: list(getattr(rule, "tags", []))
    for rule in RISK_RULE_OBJECTS
}

RULE_PRIORITIES = {
    "liability_unlimited": 100,
    "liability_cap_missing_or_unclear": 95,
    "liability_super_cap_carveout": 110,
    "liability_cap_present": 30,
    "liability_consequential_exclusion": 20,
    "indemnity_broad": 90,
    "indemnity_one_way": 80,
    "termination_for_convenience_counterparty": 70,
    "auto_renewal_silent": 50,
    "unilateral_price_increase": 80,
    "service_suspension_right": 80,
    "broad_sublicensing_right": 75,
    "broad_warranty_disclaimer": 75,
    "broad_customer_data_use": 85,
    "assignment_without_consent": 70,
    "change_of_control_assignment": 72,
    "unilateral_amendment_policy_reference": 78,
    "fee_acceleration_late_fee_exposure": 76,
    "service_credits_sole_remedy": 74,
    "publicity_name_use_rights": 45,
    "intrusive_audit_rights": 55,
    "data_retention_deletion_asymmetry": 82,
    "termination_assistance_exit_dependency": 58,
    "survival_clause_risk_concentration": 52,
    "governing_law_foreign_or_unfamiliar": 64,
    "jurisdiction_exclusive_foreign_forum": 68,
    "jurisdiction_non_exclusive_forum": 38,
    "arbitration_forum_or_seat": 62,
    "venue_burden_foreign_court": 66,
}


LABEL_ALIASES = {
    "liability_unlimited": "unlimited liability",
    "liability_cap_present": "liability cap present",
    "liability_cap_missing_or_unclear": "missing liability cap",
    "liability_super_cap_carveout": "liability carveout",
    "liability_consequential_exclusion": "consequential exclusion",
    "indemnity_broad": "broad indemnity",
    "indemnity_one_way": "one way indemnity",
    "termination_for_convenience_counterparty": "termination for convenience",
    "auto_renewal_silent": "auto renewal",
    "unilateral_price_increase": "price increase",
    "service_suspension_right": "service suspension",
    "broad_sublicensing_right": "sublicensing",
    "broad_warranty_disclaimer": "warranty disclaimer",
    "broad_customer_data_use": "data use",
    "assignment_without_consent": "assignment without consent",
    "change_of_control_assignment": "change of control assignment",
    "unilateral_amendment_policy_reference": "unilateral amendment",
    "fee_acceleration_late_fee_exposure": "fee acceleration or late fee exposure",
    "service_credits_sole_remedy": "service credits sole remedy",
    "publicity_name_use_rights": "publicity or name use rights",
    "intrusive_audit_rights": "intrusive audit rights",
    "data_retention_deletion_asymmetry": "data retention deletion asymmetry",
    "termination_assistance_exit_dependency": "termination assistance exit dependency",
    "survival_clause_risk_concentration": "survival clause risk concentration",
    "governing_law_foreign_or_unfamiliar": "selected governing law",
    "jurisdiction_exclusive_foreign_forum": "selected exclusive jurisdiction",
    "jurisdiction_non_exclusive_forum": "non exclusive dispute forum",
    "arbitration_forum_or_seat": "arbitration seat or forum",
    "venue_burden_foreign_court": "operationally burdensome dispute venue",
}


RISK_RULES = [
    {
        "label": LABEL_ALIASES.get(rule.id, rule.id),
        "weight": int(rule.weight),
        "patterns": list(rule.patterns),
    }
    for rule in RISK_RULE_OBJECTS
]
