"""add scan_input_length to scans

Revision ID: 0f5bf4901e6a
Revises: 4f0598891ff7
Create Date: 2026-03-25 05:06:04.088425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5bf4901e6a'
down_revision: Union[str, None] = '4f0598891ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('scan_input_length', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'scan_input_length')
    # ### end Alembic commands ###
