import Link from "next/link";
import SiteFooter from "../site-footer";

export function InternalShell({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) {
  return <><main className="min-h-screen bg-[#f6efe1] text-neutral-950"><header className="border-b border-[#dfd0b6] bg-[#f6efe1]"><div className="mx-auto flex max-w-[1360px] flex-col gap-5 px-5 py-5 md:flex-row md:items-center md:justify-between md:px-8"><Link href="/internal/command-centre" className="flex items-center gap-4"><div className="flex h-[76px] w-[76px] shrink-0 items-center justify-center overflow-hidden rounded-full shadow-[0_12px_28px_rgba(75,55,25,0.18)]"><img src="/brand/voxa-circle-logo.png" alt="VOXA" className="h-full w-full rounded-full object-cover object-center" /></div><div><div className="text-[20px] font-black uppercase tracking-[0.24em] text-neutral-950">VOXARISK</div><div className="mt-2 text-[11px] font-bold uppercase tracking-[0.16em] text-[#7b5d2c]">COMMAND CENTRE</div></div></Link><nav className="flex flex-wrap gap-2 text-sm">{[["Command", "/internal/command-centre"], ["Users", "/internal/users"], ["Orgs", "/internal/orgs"], ["Subscriptions", "/internal/subscriptions"], ["Revenue", "/internal/revenue"], ["Scans", "/internal/scans"], ["Audit", "/internal/audit"], ["Staff", "/internal/staff"]].map(([label, href]) => <Link key={href} href={href} className="rounded-xl border border-[#d8c49e] bg-[#fff8ea] px-4 py-2 font-semibold text-[#6f5328] transition hover:bg-[#f3e4c6]">{label}</Link>)}</nav></div></header><section className="mx-auto max-w-[1360px] px-6 py-10 md:px-8"><div className="rounded-[2rem] border border-[#dfd0b6] bg-[#fffaf0] p-7 shadow-[0_22px_60px_rgba(75,55,25,0.10)] md:p-10"><div className="flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.3em] text-[#8a6a34]"><span className="h-px w-8 bg-[#b08d57]" />{eyebrow}</div><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] text-neutral-950 md:text-5xl">{title}</h1>{children}</div></section></main><SiteFooter /></>;
}

export function Metric({ label, value, detail }: { label: string; value: React.ReactNode; detail?: string }) { return <div className="rounded-xl border border-[#d8c49e] bg-[#fbf3e5] p-4"><div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#8a6a34]">{label}</div><div className="mt-2 text-2xl font-semibold text-neutral-950">{value}</div>{detail && <div className="mt-2 text-xs leading-5 text-neutral-600">{detail}</div>}</div>; }
export function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-[1.25rem] border border-[#d8c49e] bg-[#fbf3e5] p-6"><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-[#8a6a34]">{title}</div>{children}</section>; }
